# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 13:57
from __future__ import unicode_literals

import course.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Inf',
            field=models.TextField(default='IITD course'),
        ),
        migrations.AddField(
            model_name='message',
            name='msg',
            field=models.CharField(default='Hello!', max_length=1000),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.date(2018, 3, 12)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.time(19, 27, 9, 677248)),
        ),
        migrations.AlterField(
            model_name='studcourse',
            name='date',
            field=models.DateField(default=datetime.date(2018, 3, 12), verbose_name=course.models.Student),
        ),
        migrations.AlterField(
            model_name='studcourse',
            name='time',
            field=models.TimeField(default=datetime.time(19, 27, 9, 677248)),
        ),
    ]
